/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaalgos;

public class App {
	
     public static class TreeNode {
         int val;
         TreeNode left;
         TreeNode right;
         TreeNode(int x) { val = x; }
    }
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
	
	public static TreeNode inorderSuccessor(TreeNode r, TreeNode p) {
		return null;
	}
}
