/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaalgos;
import java.util.List;
import java.util.ArrayList;

public class App {
	
     public static class TreeNode {
         int val;
         TreeNode left;
         TreeNode right;
         TreeNode(int x) { val = x; }
		 public String toString() {
			 return val+"";
		 }
    }
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
	
	public static TreeNode inorderSuccessor(TreeNode r, TreeNode p) {
		TreeNode a = null;
		while(r != null) {
			if(r.val > p.val) {
				a = r;
				r = r.left;
			}else {
				r = r.right;
			}
		}
		return a;
	}	
}
