/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
    mavenLocal()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:29.0-jre")
    implementation("org.jgrapht:jgrapht-core:1.5.2")
}

application {
    // Define the main class for the application.
    mainClass.set("javaalgos.App")
}

tasks {
    test {                                  
        testLogging.showExceptions = true
		testLogging.showStandardStreams = true
		testLogging.events("failed")
    }
}